### ISSUE TITLE
The Fine-tuned T5 Checkpoint

### ISSUE THREAD

**Issue by t1101675** [ruiqi-zhong/DescribeDistributionalDifferences#1]
Could you please share the checkpoint of the fine-tuned T5 proposer? It would be a great help for further research. Thanks!

**Comment by ruiqi-zhong** [comment]
Our model can be accessed through hugging face: ruiqi-zhong/t5proposer_0514 . Feel free to let me know whether the provided programs don't work or if you have trouble accessing the model. Thanks a lot!!

**Comment by t1101675** [comment]
Thank you so much for your quick reply! I will try it :)
